version: '2'

services:
  salt-master:
    image: saltstack/salt:3000
    container_name: salt-master
    ports:
      - "4505:4505"
      - "4506:4506"
    volumes:
      - $PWD/../salt:/srv/salt
      - $PWD/../pillar:/srv/pillar
      - $PWD/files/master.conf:/etc/salt/master.d/master.conf
