

#### CONFIGURATION CONSTANTS ####

VAGRANTFILE_API_VERSION = '2' unless defined? VAGRANTFILE_API_VERSION

# DO NOT change the VM_IMAGE_URL to an actual URL or you will likely break vagrant for everyone on Windows
VM_NAME = 'Test Salt Minion' unless defined? VM_NAME

#################################

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.box = 'ubuntu/bionic64'

  config.vm.provision "file", source: "./files/minion", destination: "./minion"

  config.vm.provider :virtualbox do |vb, override|
    if defined? VM_MEMORY
      vb.customize ["modifyvm", :id, "--memory", VM_MEMORY]
    end

    if defined? VM_CPU_CAP
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", VM_CPU_CAP]
    end

    vb.name = VM_NAME
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /etc/salt 
    cp ./minion /etc/salt/minion
    curl -o bootstrap_salt.sh -L https://bootstrap.saltstack.com && sh bootstrap_salt.sh -A 10.0.2.2 -i minion.vagrant
    salt-call grains.append fqdn_ip4 $(ip addr show scope 0 | grep inet | awk '{print $2}' | awk -F "/" '{print $1}')
    salt-call saltutil.sync_all
    
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-get update && apt-get install -y docker-ce python-docker
  SHELL
end
