version: '2'

services:
  salt-master:
    image: saltstack/salt:3000
    container_name: salt-master
    ports:
      - "4505:4505"
      - "4506:4506"
    environment: 
      SALT_MASTER_CONFIG: '{"auto_accept": true}'
    volumes:
      - $PWD/../salt:/srv/salt
      - $PWD/../pillar:/srv/pillar
      # - $PWD/files/master.conf:/etc/salt/master.d/master.conf
      # - $PWD/files/minion.conf:/etc/salt/minion.d/minion.conf
      - $PWD/../tests/:/tests/

  salt-minion:
    image: saltstack/salt:3000
    container_name: salt-minion
    environment: 
      SALT_MINION_CONFIG: '{"id": "test.minion", "master": "salt-master", "nexus3": {"hostname": "http://nexus3:8081", "username": "admin", "password": "admin123"}}'
    links:
      - salt-master:salt-master
      - nexus3:nexus3

  nexus3:
    image: sonatype/nexus3:latest
    container_name: nexus3
    ports:
      - "8081:8081"
      - "5000:5000"